# TodoApp/todo-frontend/Dockerfile.dev
FROM node:24-alpine

WORKDIR /usr/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

# WDS needs to listen on all interfaces
CMD ["npm", "start"]
