version: "3.8"
services:

  todo-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/usr/app/nodemon.json
    command: node build/index.js
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb/todo"
      # Change this to use .env variable on prod
      JWT_SECRET: ${JWT_SECERT}
    container_name: todo_backend
    restart: unless-stopped

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./db:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped