version: "3.8"
services:

  todo-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/app/src
      - ./nodemon.json:/usr/app/nodemon.json
    command: npm run dev
    ports:
      - "7999:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb/todo"
      JWT_SECRET: "supersecretkey"
    container_name: todo_backend
    restart: unless-stopped

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./db:/data/db:cached
    ports:
    - 27017:27017
    restart: unless-stopped