
build-dev:
	docker-compose up --build
build-prod:
	docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build
up-dev:
	docker-compose up
up-prod:
	docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
down: 
	docker-compose down