name: Build and Push TodoApp

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build and Push Projects
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Build and Push Backend
        run: |
          echo "Building and Pushing Backend..."
          make -C todo-backend buildx-push

      - name: Build and Push Frontend
        run: |
          echo "Building and Pushing Frontend..."
          make -C todo-frontend buildx-push
